### PR TITLE
Remove Keith Cirkel (now part of MicrosoftWHATWGContributors)

### PR DESCRIPTION
**Pull request by keithamus**
Hi :wave: 

I raised this PR to verify myself, to get https://github.com/whatwg/html/pull/9195 passing. Hopefully me filing this PR with my GPG signature acts as another vector for verification.

### CODE REVIEW

**Comment by annevk** [comment]
Hey Keith!

Since you are GitHub staff are you not employed by Microsoft? In that case you should ask internally to be part of the MicrosoftWHATWGContributors organization.

**Comment by keithamus** [comment]
I can do that.

**Comment by annevk** [comment]
It would be a lot easier if you could go via Microsoft's established path, but reading https://whatwg.org/ipr-policy#2101-work-in-the-field-of-web-technologies again you might be eligible for individual participation I suspect. I will check.

**Comment by annevk** [comment]
Note that Microsoft has signed, you "just" need to join https://github.com/MicrosoftWHATWGContributors and make your membership public.

**Comment by keithamus** [comment]
https://github.com/orgs/MicrosoftWHATWGContributors/people#member-keithamus took a minute but I've managed to join the org.

**Comment by annevk** [comment]
Great, then you can turn this into a "Remove Keith" PR :-)

**Comment by keithamus** [comment]
@annevk done :smile:

**Pull request merged**
