### PR TITLE
adding myself to the list of contributors

### PR DESCRIPTION
**Pull request by gked**
To pass a PR check, I needed to add myself as a contributor. So doing just that;
PR for reference: https://github.com/whatwg/html/pull/5264

### CODE REVIEW

**Comment by annevk** [comment]
This is not how this works. You should talk to @travisleithead about getting yourself added to https://github.com/MicrosoftWHATWGContributors. Could we make this clearer somewhere to lead future folks less astray?

**Comment by domenic** [comment]
I think we could add something to the readme of this repository to make sure that people don't send pull requests, perhaps.

**Comment by michaelchampion** [comment]
I submitted a PR on the readme file for this repo describing the context and workflow in more detail.   https://github.com/whatwg/participant-data/pull/19

**Comment by michaelchampion** [comment]
But I wonder if that is too deeply buried to be useful for people in @gked 's situation?  Maybe make the workflow  for those affiliated with Entities clearer in https://participate.whatwg.org/ or even https://whatwg.org/faq ?  

I know I struggled to remember exactly what to do while I was Microsoft's contact .... 

And BTW @travisleithead , you should remove me as a contact in Microsoft's entry now that I've retired.

**Comment by domenic** [comment]
+1 to modifying the front page of participate.whatwg.org. It'd still be good to have something here as a "last ditch", if people find there way to this repo. But ideally nobody should ever be spending time on this repo except automated tools and people/organizations doing maintenance on their contact info.

**Comment by gked** [comment]
@travisleithead as FYI
@annevk  and @domenic so should I abandon this PR? 
@michaelchampion thank you for clarifying the message.

My two cents on the process: I wonder if it is possible to have a PR check that would fail immediately if the person updating entities.json file is not defined in the "signature" object.  Or another thought; having the authorized person added to the PR if their respective entity is being updated.

**Comment by domenic** [comment]
I'm not sure how much we need to invest in automated tooling for scenarios like this. Humans should rarely interact with this repo, and when they do, we can have other humans check their work.

And yes, unless you want to become Microsoft's new legal contact for the WHATWG, you should probably abandon this PR. (Becoming their legal contact is unrelated to being a contributor that passes the IPR check, to be clear.)

**Pull request closed without merging**
