### PR TITLE
Verify Keio University

### PR DESCRIPTION
**Pull request by foolip**
Also fix Mike's GitHub ID.

### CODE REVIEW

**Comment by annevk** [comment]
Verification is triggered by a corresponding contribution.

**Comment by sideshowbarker** [comment]
I think https://github.com/whatwg/participant-data#maintenance is where the process is documented:

> Whenever an individual or entity signs the agreement, an entry is added to the respective JSON file with the `verified` field set to false. When they then make a contribution, the respective editor will [check everything is in order](https://github.com/whatwg/participate.whatwg.org#process-for-editors "Process for Editors") and set the `verified` field to true or escalate as appropriate. If they do not end up contributing their `verified` field likely is not changed.

The good news is, I already have PRs that’ve been waiting til we could get the participant-agreement situation unblocked:

* https://github.com/whatwg/html/pull/4047
* https://github.com/whatwg/html/pull/3948
* https://github.com/whatwg/html/pull/3866

I need to look back at each of them and see if they’re still relevant to the current spec (rather than having been superseded by other changes in the meantime), and need to rebase them. But in parallel to that, any of the HTML spec editors can also be reviewing them see. If any of them are still relevant, then after rebasing, we can apply the normal process steps (cited above) to get the participant data updated. (I don’t know, though, if that happens before a PR is merged, or after…)

**Comment by foolip** [comment]
Thanks for pointing out the docs. It sounds like there's no issue at all verifying before one comes across a PR blocked on it, which in this care there already are though. I see that we don't have branch protection for this repo, but if someone wants to approve it, that'd be great.

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
In fact, we usually commit directly to master. 😊

**Comment by foolip** [comment]
I see. Maybe next time I'll feel daring :)

**Pull request merged**
